"""
=========================================================
Pulse Sequence Viewer
=========================================================

Reusable widget for visualizing digital pulse sequences.

This widget is experiment independent and can be reused
for:

    • ODMR
    • Pulsed ODMR
    • Rabi
    • Ramsey
    • T1
    • T2
    • XY8
    • DEER
    • Custom pulse sequences

Author:
    NV Control Framework

=========================================================
"""

from PyQt6.QtWidgets import ( # type: ignore
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QGraphicsRectItem,
)

from PyQt6.QtCore import Qt # type: ignore

import pyqtgraph as pg # type: ignore


# =========================================================
# DEFAULT CHANNEL COLORS
# =========================================================

CHANNEL_COLORS = {

    "greenLaser": "#228B22",      # Forest Green
    "MW": "#DC143C",              # Crimson
    "detector": "#1E90FF",        # Dodger Blue

}


# =========================================================
# PULSE SEQUENCE VIEWER
# =========================================================

class PulseSequenceViewer(QWidget):

    """
    Generic digital pulse sequence viewer.

    The viewer displays the actual PulseSequence object
    generated by an experiment.

    It has no knowledge of ODMR, Rabi, Ramsey, etc.

    Only PulseSequence + channel_map.
    """

    # =====================================================
    # INITIALIZATION
    # =====================================================

    def __init__(self, parent=None):

        super().__init__(parent)

        self.sequence = None

        self.channel_map = {}

        self.channel_positions = {}

        self.channel_height = 0.60

        self.channel_spacing = 2.50

        self.build_gui()

    # =====================================================
    # BUILD GUI
    # =====================================================

    def build_gui(self):

        main_layout = QVBoxLayout(self)

        # -------------------------------------------------
        # TOOLBAR
        # -------------------------------------------------

        toolbar = QHBoxLayout()

        self.reset_button = QPushButton(
            "Reset Zoom"
        )

        toolbar.addWidget(
            self.reset_button
        )

        toolbar.addStretch()

        main_layout.addLayout(
            toolbar
        )

        # -------------------------------------------------
        # PLOT
        # -------------------------------------------------

        self.plot = pg.PlotWidget()

        self.plot.setBackground("w")

        self.plot.showGrid(
            x=True,
            y=True,
            alpha=0.30
        )

        self.plot.getAxis("bottom").setStyle(

            tickTextOffset=10

        )

        self.plot.getAxis("bottom").setLabel(

            "Time",

            units="ms"

        )

        self.plot.setLabel(
            "bottom",
            "Time (ms)"
        )

        self.plot.showAxis("left")

        self.plot.setMenuEnabled(
            True
        )

        self.plot.setMouseEnabled(
            x=True,
            y=False
        )

        self.plot.enableAutoRange()

        main_layout.addWidget(
            self.plot
        )

        # -------------------------------------------------
        # STATUS BAR
        # -------------------------------------------------

        self.info_label = QLabel()

        self.info_label.setAlignment(
            Qt.AlignmentFlag.AlignLeft
        )

        main_layout.addWidget(
            self.info_label
        )

        # -------------------------------------------------
        # CONNECTIONS
        # -------------------------------------------------

        self.reset_button.clicked.connect(
            self.reset_view
        )

    # =====================================================
    # PUBLIC API
    # =====================================================

    def set_sequence(
        self,
        sequence,
        channel_map=None
    ):

        self.sequence = sequence

        if channel_map is None:
            channel_map = {}

        self.channel_map = channel_map

        self.refresh()

    # =====================================================
    # CLEAR VIEW
    # =====================================================

    def clear(self):

        self.plot.clear()

        self.info_label.clear()

    # =====================================================
    # REFRESH
    # =====================================================

    def refresh(self):

        self.clear()
        self.plot.setTitle(

            "<span style='font-size:16pt'>"
            "<b>Pulse Sequence Inspector</b>"
            "</span>"
        )

        if self.sequence is None:

            self.info_label.setText(
                "No pulse sequence loaded."
            )

            return

        self.compute_channel_positions()

        self.draw_channels()

        self.update_statistics()

        self.reset_view()
    # =====================================================
    # COMPUTE CHANNEL POSITIONS
    # =====================================================
    def compute_channel_positions(self):

        self.channel_positions.clear()

        pulses = self.sequence.digital_pulses

        channels = sorted(
            list(
                set(
                    p.channel
                    for p in pulses
                )
            )
        )

        n = len(channels)

        # ---------------------------------------------
        # Compute vertical positions
        # ---------------------------------------------
        for i, ch in enumerate(channels):

            self.channel_positions[ch] = (
                (n - i)
                * self.channel_spacing
            )

        # ---------------------------------------------
        # Set Y-axis labels
        # ---------------------------------------------
        ticks = []

        for ch in channels:

            ticks.append(

                (
                    self.channel_positions[ch]
                    + self.channel_height / 2,

                    self.get_channel_name(ch)

                )

            )

        self.plot.getAxis("left").setTicks(
            [ticks]
        )
    
    # =====================================================
    # DRAW ALL CHANNELS
    # =====================================================

    def draw_channels(self):

        pulses = self.sequence.digital_pulses

        channels = sorted(
            list(
                set(
                    p.channel
                    for p in pulses
                )
            )
        )

        xmax = 0

        for ch in channels:

            self.draw_channel(ch)

        for pulse in pulses:

            xmax = max(
                xmax,
                pulse.end_ns
            )

        self.plot.setXRange(
            0,
            xmax / 1e6 * 1.05
        )

        self.plot.setYRange(
            0,
            (len(channels) + 1)
            * self.channel_spacing
        )

    # =====================================================
    # DRAW ONE CHANNEL
    # =====================================================

    def draw_channel(
        self,
        channel
    ):

        pulses = [

            p

            for p in self.sequence.digital_pulses

            if p.channel == channel

        ]

        if len(pulses) == 0:
            return

        y0 = self.channel_positions[channel]

        y1 = (
            y0
            + self.channel_height
        )

        # ------------------------------------------
        # Channel name
        # ------------------------------------------

        channel_name = self.get_channel_name(channel)

        pulse_name = self.get_channel_name(
            channel,
            short=True
        )

        color = self.get_channel_color(channel)
        # ------------------------------------------
        # LOW baseline
        # ------------------------------------------

        xmax = max(
            p.end_ns
            for p in pulses
        ) / 1e6

        self.plot.plot(

            [0, xmax],

            [y0, y0],

            pen=pg.mkPen(
                "#bbbbbb",
                width=1
            )

        )

        # ------------------------------------------
        # HIGH pulse(s)
        # ------------------------------------------

        for pulse in pulses:

            start = pulse.start_ns / 1e6

            end = pulse.end_ns / 1e6

            rect = QGraphicsRectItem(

                start,

                y0,

                end - start,

                self.channel_height

            )

            rect.setPen(

                pg.mkPen(
                    color,
                    width=2
                )

            )

            rect.setBrush(

                pg.mkBrush(
                    color
                )

            )

            self.plot.addItem(rect)

            text = pg.TextItem(

                pulse_name,

                color="black",

                anchor=(0.5, 0.35)

            )

            text.setPos(

                (start + end) / 2,

                y0 + self.channel_height / 2

            )

            self.plot.addItem(text)
    # =====================================================
    # UPDATE STATISTICS
    # =====================================================

    def update_statistics(self):

        pulses = self.sequence.digital_pulses

        if len(pulses) == 0:

            self.info_label.setText(
                "No digital pulses."
            )

            return

        total_time_ns = max(
            pulse.end_ns
            for pulse in pulses
        )

        total_time_ms = total_time_ns / 1e6

        n_channels = len(
            self.channel_positions
        )

        self.info_label.setText(

            f"<b>Channels:</b> {n_channels}"

            f"&nbsp;&nbsp;&nbsp;&nbsp;"

            f"<b>Digital Pulses:</b> {len(pulses)}"

            f"&nbsp;&nbsp;&nbsp;&nbsp;"

            f"<b>Sequence Length:</b> "

            f"{total_time_ms:.3f} ms"

        )

    # =====================================================
    # RESET VIEW
    # =====================================================

    def reset_view(self):

        self.plot.enableAutoRange()

    # =====================================================
    # GET CHANNEL NAME
    # =====================================================

    def get_channel_name(self, channel, short=False):

        for name, number in self.channel_map.items():

            if number == channel:

                if short:

                    short_names = {
                        "greenLaser": "Laser",
                        "detector": "Camera",
                        "MW": "MW",
                    }

                    return short_names.get(name, name)

                pretty_names = {
                    "greenLaser": "Green Laser",
                    "detector": "Camera",
                    "MW": "MW",
                }

                return pretty_names.get(name, name)

        return str(channel)
    # =====================================================
    # GET CHANNEL COLOR
    # =====================================================
    def get_channel_color(self, channel):

        for name, number in self.channel_map.items():

            if number == channel:

                return CHANNEL_COLORS.get(
                    name,
                    "#555555"
                )

        return "#555555"
    # =====================================================
    # GET TOTAL SEQUENCE TIME
    # =====================================================

    def get_total_time_ms(self):

        if self.sequence is None:

            return 0

        pulses = self.sequence.digital_pulses

        if len(pulses) == 0:

            return 0

        total_ns = max(
            pulse.end_ns
            for pulse in pulses
        )

        return total_ns / 1e6

    # =====================================================
    # GET NUMBER OF CHANNELS
    # =====================================================

    def get_channel_count(self):

        return len(
            self.channel_positions
        )